import type { NextPage } from "next";
import Head from "next/head";

import Search from "@/components/Search/Search";

import styles from "styles/pages/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.homeContainer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Search />
    </div>
  );
};

export default Home;
